/*
 * generated by Xtext 2.13.0
 */
package de.mayjs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EclipseOpenScadStandaloneSetup extends EclipseOpenScadStandaloneSetupGenerated {

	def static void doSetup() {
		new EclipseOpenScadStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
