/*
 * generated by Xtext 2.13.0
 */
package de.mayjs


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EclipseOpenScadRuntimeModule extends AbstractEclipseOpenScadRuntimeModule {
}
